spring.application.name=projectjwt1

spring.security.user.name = manish
spring.security.user.password = manish

spring.datasource.url=jdbc:postgresql://localhost:5433/tryjwt
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

exception.clientNotRegisterException = Registration of Client is failed
success.clientRegister = Registration is done successfully



# Set log levels (optional, based on your needs)
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.com.company.projectjwt1=DEBUG

# Log file configuration
logging.file.name=myLogInfoFile.log
